blank_issues_enabled: false
contact_links:
  - name: "ðŸ’¬ Discussions"
    url: https://github.com/VOTRE_USER/secure-python-pipeline/discussions
    about: "Questions gÃ©nÃ©rales et discussions"
  - name: "ðŸ“– Documentation"
    url: https://github.com/VOTRE_USER/secure-python-pipeline#readme
    about: "Consultez la documentation avant de poser une question"
